update build script, get makefile to work

diff --git a/release b/release
--- a/release
+++ b/release
@@ -11,64 +11,56 @@ usage()
 fetcharch()
 {
     if [ "$ARCH" != "" ]; then
-	echo "ARCH forcibly set to ${ARCH} - using it instead"
-	return
+        echo "ARCH forcibly set to ${ARCH} - using it instead"
+        return
     fi
-	
+    
     if [ -x /usr/bin/arch -o -x /bin/arch ]; then
-	ARCH=`arch`
-	return
+        ARCH=`arch`
+        return
     fi
 
     if [ -x /usr/bin/uname -o -x /bin/uname ]; then
-	ARCH=`uname -m`
-	return
+        ARCH=`uname -m`
+        return
     fi
 
     if [ "$ARCH" == "" ]; then
-	echo "$0 uses 'arch' or 'uname' which appear to be missing"
-	exit 1
+        echo "$0 uses 'arch' or 'uname' which appear to be missing"
+        exit 1
     fi
 }
 
 fetchversion()
 {
     if [ $# -ne 2 ]; then
-	echo "This option requires exactly 2 arguments"
-	usage
+        echo "This option requires exactly 2 arguments"
+        usage
     fi
 
     VERSION=$2
 
     if ! echo $VERSION | grep -E '^[0-9]+[.][0-9]+$' > /dev/null; then
-	echo "<VERSION> should be in the format <MAJOR>.<MINOR>"
-	usage
+        echo "<VERSION> should be in the format <MAJOR>.<MINOR>"
+        usage
     fi
 }
 
 buildrootfs()
 {
-    case "${ARCH}" in
-	x86_64)
-	    URL="http://ftp.morpheus.net/pub/linux/crux/crux-${VERSION}/iso/crux-${VERSION}.iso"
-	    ;;
-	aarch64)
-	    URL="http://resources.crux-arm.nu/releases/${VERSION}/crux-arm-rootfs-${VERSION}-aarch64.tar.xz"
-	    ;;
-    esac
-
     if docker ps -a | grep -q cruxbuild; then
-	docker rm -f cruxbuild > /dev/null
+        docker rm -f cruxbuild > /dev/null
     fi
 
     docker build -t cruxbuild build/${ARCH}
 
     docker run \
-	   -i -t --privileged \
-	   --name cruxbuild \
-	   -e URL=${URL} \
-	   -e VERSION=${VERSION} \
-	   cruxbuild
+       -i -t --privileged \
+       --name cruxbuild \
+       -e ISO_FILENAME=${ISO_FILENAME} \
+       -e ISO_URL=${ISO_URL} \
+       -e VERSION=${VERSION} \
+       cruxbuild
 
     docker cp cruxbuild:/buildenv/rootfs.tar.xz .
     docker rm -f cruxbuild > /dev/null
@@ -77,14 +69,14 @@ buildrootfs()
 committobranch()
 {
     if [ ! -e rootfs.tar.xz ]; then
-	echo "Can't find rootfs.tar.xz is it built (see: 'build' arg)?"
-	exit 1
+        echo "Can't find rootfs.tar.xz is it built (see: 'build' arg)?"
+        exit 1
     fi
 
     BRANCH=${VERSION}-${ARCH}
 
     if git show-ref --verify --quiet refs/heads/${BRANCH}; then
-	git branch -D ${BRANCH}
+        git branch -D ${BRANCH}
     fi
 
     git fetch origin
@@ -102,14 +94,14 @@ testing()
     TAG=${BRANCH}-test
 
     if ! git show-ref --verify --quiet refs/heads/${BRANCH}; then
-	echo "Can't test release ${BRANCH} is it committed (see: 'commit' arg)?"
-	exit 1
+        echo "Can't test release ${BRANCH} is it committed (see: 'commit' arg)?"
+        exit 1
     fi
 
     git checkout ${BRANCH}
 
     if docker ps -a | grep -q ${BRANCH}; then
-	docker rm -f ${BRANCH} > /dev/null
+        docker rm -f ${BRANCH} > /dev/null
     fi
 
     docker build -t ${TAG} .
@@ -146,37 +138,37 @@ library()
     echo "GitCommit: ${mastersha}"
 
     for v in `git branch -r | grep -E ${REMOTE}/release-[0-9]+[.][0-9]+ | grep -Eo [0-9]+[.][0-9]+`; do
-	VERSIONS="$VERSIONS $v"
+        VERSIONS="$VERSIONS $v"
     done
     VERSIONS=$(echo $VERSIONS | tr " " "\n" | sort -Vr | uniq | tr "\n" " ")
 
     for v in $VERSIONS; do
-	OUTPUT=""
-	ARCHES=""
+        OUTPUT=""
+        ARCHES=""
 
-	for b in `git branch -r | grep -E ${REMOTE}/release-$v`; do
-	    head=${b##*/}
-	    sha=$(git log --format="%H" -n1 ${b})
-	    arch=$(echo ${b} | cut -d '-' -f 3)
+        for b in `git branch -r | grep -E ${REMOTE}/release-$v`; do
+            head=${b##*/}
+            sha=$(git log --format="%H" -n1 ${b})
+            arch=$(echo ${b} | cut -d '-' -f 3)
 
-	    # Docker Hub has an odd nomenclature for architectures
-	    arch=$(echo ${arch} | sed 's/x86_64/amd64/' | sed 's/aarch64/arm64v8/')
+            # Docker Hub has an odd nomenclature for architectures
+            arch=$(echo ${arch} | sed 's/x86_64/amd64/' | sed 's/aarch64/arm64v8/')
 
-	    ARCHES="${ARCHES} $arch,"
+            ARCHES="${ARCHES} $arch,"
 
-	    OUTPUT="$OUTPUT$arch-GitFetch: refs/heads/$head\n"
-	    OUTPUT="$OUTPUT$arch-GitCommit: $sha\n"
-	done
+            OUTPUT="$OUTPUT$arch-GitFetch: refs/heads/$head\n"
+            OUTPUT="$OUTPUT$arch-GitCommit: $sha\n"
+        done
 
-	ARCHES=$(echo $ARCHES | tr " " "\n" | sort | uniq | tr "\n" " ")
+        ARCHES=$(echo $ARCHES | tr " " "\n" | sort | uniq | tr "\n" " ")
 
-	echo ""
-	echo  "Tags: ${v}${latest}"
-	echo  "Architectures: ${ARCHES%, }"
-	echo -e ${OUTPUT%'\n'}
+        echo ""
+        echo  "Tags: ${v}${latest}"
+        echo  "Architectures: ${ARCHES%, }"
+        echo -e ${OUTPUT%'\n'}
 
-	# Only tag the first, most recent version as latest"
-	latest=""
+        # Only tag the first, most recent version as latest"
+        latest=""
     done
 }
 
@@ -185,28 +177,28 @@ main() {
 
     # TODO: Add more options (commit, push, etc)
     case "$1" in
-	build)
-	    fetchversion "$@"
-	    buildrootfs "$@"
-	    ;;
-	commit)
-	    fetchversion "$@"
-	    committobranch "$@"
-	    ;;
+        build)
+            fetchversion "$@"
+            buildrootfs "$@"
+            ;;
+        commit)
+            fetchversion "$@"
+            committobranch "$@"
+            ;;
         test)
-	    fetchversion "$@"
-	    testing "$@"
-	    ;;
+            fetchversion "$@"
+            testing "$@"
+            ;;
         push)
-	    fetchversion "$@"
-	    push "$@"
-	    ;;
+            fetchversion "$@"
+            push "$@"
+            ;;
         library)
-	    library "$@"
-	    ;;
+            library "$@"
+            ;;
         *)
-	    echo "Unrecognised argument $1"
-	    ;;
+            echo "Unrecognised argument $1"
+            ;;
     esac
 }
 
